@extends('layouts/app')
@section('main_sponser')
    @include('fe.sponser')
@endsection
@section('aboutus')
    @include('fe.aboutus')
@endsection
@section('whyussection')
    @include('fe.whyussection')
@endsection
@section('skillsection')
    @include('fe.skillsection')
@endsection
@section('servicesection')
    @include('fe.servicesection')
@endsection
@section('portfolio')
    @include('fe.portfolio')
@endsection
@section('teamsection')
    @include('fe.teamsection')
@endsection
@section('price')
    @include('fe.pricesection')
@endsection